apiVersion: v1
kind: ConfigMap
metadata:
  name: jackapp-importacao-configmap
data:
  NODE_ENV: local
  AWS_REGION: us-east-1
  SQS_QUEUE_URL: http://localhost:4566/000000000000/sqs-canal-de-processamento
  AWS_SNS_VIDEO_IMPORT_TOPIC_ARN: arn:aws:sns:us-east-1:123456789012:sns-canal-de-processamento
  AWS_SQS_DLQ_URL: http://localhost:4566/000000000000/sns-dlq-canal-de-processamento
  S3_BUCKET_NAME: video-importing-bucket
  
  